name: build godot for windows
on: [workflow_dispatch]
jobs:
  build-me:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: ./build.sh 4.5 f42
      - run: wget https://github.com/godotengine/godot/releases/download/4.5-stable/godot-4.5-stable.tar.xz
      - run: tar -xaf godot-4.5-stable.tar.xz
      - run: cd godot-4.5-stable && podman run --rm --mount type=bind,src=.,dst=/root localhost/godot-windows:4.5-f42 scons platform=windows
