name: build godot for windows
on: [workflow_dispatch]
jobs:
  build-me:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: ./build.sh 4.5 f42
      - run: podman image save -o godot-build.tar localhost/godot-windows:4.5-f42
      - uses: actions/upload-artifact@v4
        with:
          name: godot-build
          path: godot-build.tar
  build-godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: godot-build
      - run: podman image load -i godot-build.tar
      - run: curl -O https://github.com/godotengine/godot/releases/download/4.5-stable/godot-4.5-stable.tar.xz
      - run: tar -xaf godot-4.5-stable.tar.xz
      - run: podman run --rm --mount type=bind,src=${{ github.workspace }},dst=/root scons platform=windows
