name: Building godot
on: workflow_dispatch
jobs:
  build-godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: godot-build
      - run: podman image load -i godot-build.tar
      - run: curl -O https://github.com/godotengine/godot/releases/download/4.5-stable/godot-4.5-stable.tar.xz
      - run: tar -xaf godot-4.5-stable.tar.xz
      - run: podman run --rm --mount type=bind,src=${{ github.workspace }},dst=/root scons platform=windows
